on:
  push:
    branches:
      - master
jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "x86_64-pc-windows-gnu"
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ./source/gammon-lib
            ./source/gammon-windows
      - run: apt-get install mingw-w64
      - run: cargo build --release --artifact-dir artifacts
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*
