on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "x86_64-pc-windows-gnu"
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            ./source/gammon-lib
            ./source/gammon-windows
      - run: |
          set -xeu
          sudo apt-get install mingw-w64
          export ARTIFACTS="$(pwd)"/artifacts
          mkdir -p "$ARTIFACTS"
          export TARGET="$(pwd)/target"
          mkdir -p "$TARGET"
          (cd source/gammon-windows; cargo build --release --target-dir "$TARGET")
          find "$TARGET"
          cp "$TARGET"/x86_*/*.exe "$ARTIFACTS"/
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*
